### ISSUE TITLE
Date Time thrown out at the server side

### ISSUE THREAD

**Issue by adulojusm** [dhis2/dhis2-android-capture-app#2067]
**Describe the bug**
Enrollment Date, Incident Date are not accepted from the App, they generate an error and the only date are been captured.

**To Reproduce**
1. Enroll a new Tracked Entiy on the a program
2. Click on 'sync'

**Expected behavior**
Synced with no error

**Error found**
Apr 15 14:51:33 dhis2 tomcat9[290]: Field error in object 'trackedEntityInstanceCriteria' on field 'programStartDate': rejected value [2021-03-15 15:50:55.311]; codes [typeMismatch.trackedEntityInstanceCriteria.programStartDate,typeMismatch.programStartDate,typeMismatch.java.util.Date,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [trackedEntityInstanceCriteria.programStartDate,programStartDate]; arguments []; default message [programStartDate]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'programStartDate'; nested exception is java.lang.IllegalArgumentException: Invalid format: "2021-03-15 15:50:55.311" is malformed at " 15:50:55.311"]

**Any device**
This occure at any device we tried it on

**Additional context**
We only have date and no time on the registration date of the tracked entity, this is going on for event on the stages too.

**Comment by Balcan** [comment]
Hi @adulojusm,
What version of the app are you using? This was a know bug which was already fixed:
https://jira.dhis2.org/browse/ANDROAPP-2963?jql=project%20%3D%20ANDROAPP%20AND%20text%20~%20%22enrollment%20date%22
