### ISSUE TITLE
error while building dhis2 capture app

### ISSUE THREAD

**Issue by Lucifer-lab74** [dhis2/dhis2-android-capture-app#2125]
Hey , I just cloned this repo and tried to build. there were so many upgrades in dependencies so 1st I solve them. But while building apk or release apk I am getting error at dhis2-rule-engine:compile Java
> java.lang.NoClassDefFoundError: javax/annotation/Generated
Anyone can help me to solve this....Thanks....

**Comment by Balcan** [comment]
Hi @Lucifer-lab74,

Have you follow the wiki on how to clone the project? [You can find it here.](https://github.com/dhis2/dhis2-android-capture-app/wiki/Getting-the-source-code)
The dhis2 android app relies in two modules, the [dhis2 android sdk](https://github.com/dhis2/dhis2-android-sdk) and the [rule engine](https://github.com/dhis2/dhis2-rule-engine). These two modules have to be cloned as well in the project.

If you build in release from the master branch, the sdk and the rule engine will not use the modules but instead use the releaseImplementation dependency in the build.gradle pointing to their last release versions. In the other hand, if you want to build in debug, you have to make sure that each module is in the correct branch and commit.
