### ISSUE TITLE
Can't resolve some dependencies 

### ISSUE THREAD

**Issue by Lucifer-lab74** [dhis2/dhis2-android-capture-app#2126]
While building debug or release apk. Dependencies from maven kajuka not accessible. I also tried their instructions to access with github key. But doesn't solve the problem.

**Comment by Balcan** [comment]
Hi @Lucifer-lab74,
Kujaku dependency relied on jcenter repository, which has shut down recently.  That's what causing the error.
Just comment the kujaku dependency and restore the mapbox ones (I think they are commented next to the kujaku, or check the develop brach where we have just did this).

Let me know if this worked for you :)

**Comment by Lucifer-lab74** [comment]
Yeah thanks a lot.....
