### ISSUE TITLE
sync setting

### ISSUE THREAD

**Issue by WKui1997** [dhis2/dhis2-android-capture-app#2299]
I spend a lot of time syncing each time. If I only want to sync the data of the past three days, how should I modify it?

**Comment by andresmr** [comment]
Hello, actually our [SDK](https://github.com/dhis2/dhis2-android-sdk) does not expose any method to limit this. You could use the Android web settings app which you can find in the marketplace, there you can limit as minimum to a month.
Anyway in each update we used _lastUpdated_ parameter, so only updated data should be downloaded each time.
Hope it can helps you!.
