### ISSUE TITLE
How to change the google maps service url?

### ISSUE THREAD

**Issue by linxd** [dhis2/dhis2-android-capture-app#340]
we have a different map service URL in china, how to change url config?

**Comment by Balcan** [comment]
Hi linxd!
We are using google map api, so it is not possible to simply change the url. It requires to re-write all maps functionality.
We are going to change how maps are integrated in the app to fix this issue. If possible, could you please report it in jira (https://jira.dhis2.org/) so we can provide a proper follow up?
Thank you!

**Comment by linxd** [comment]
Thanks. sir.



need rewrite with  just  change https://www.google.com/maps/ to https://www.google.cn/maps???



--

此致

   林晓东

莫愁前路无知己，天下谁人不识君。

At 2019-04-15 18:54:10, "Pablo" <notifications@github.com> wrote:


Hi linxd!
We are using google map api, so it is not possible to simply change the url. It requires to re-write all maps functionality.
We are going to change how maps are integrated in the app to fix this issue. If possible, could you please report it in jira (https://jira.dhis2.org/) so we can provide a proper follow up?
Thank you!
