### ISSUE TITLE
Could not find play-services-basement.aar

### ISSUE THREAD

**Issue by linxd** [dhis2/dhis2-android-capture-app#82]
* What went wrong:
Could not resolve all files for configuration ':app:alphaCompileClasspath'.
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

**Comment by Balcan** [comment]
Have to change jcenter() to last place in the build.gradle files:

buildscript {
    ...
    repositories {
        google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        jcenter()
    }...

and

allprojects {
    repositories {
        google()
        jcenter()
    }
  }

**Comment by linxd** [comment]
Thanks.

在 2018-10-31 00:59:23，"Pablo" <notifications@github.com> 写道：


Have to change jcenter() to last place in the build.gradle files:

buildscript {
...
repositories {
google()
maven {
url 'https://maven.google.com/'
name 'Google'
}
jcenter()
}...

and

allprojects {
repositories {
google()
jcenter()
}
}
