### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ahmedifhaam** [dhis2/dhis2-android-capture-app#87]
Since the total architecture is different from earlier versions it would be very useful if you can release at least an top level documentation it would be much useful to understand

**Comment by Balcan** [comment]
Hi @ahmedifhaam

You are totally right. The code can be a little bit confusing to follow due to rxjava and dagger been used. We have an internal document but are working on exposing something more user-friendly.
It will be post on the Wiki in the next weeks hopefully.

**Comment by sunbiz** [comment]
Anything yet on this? The Wiki is still empty
